
import { OPD, Role, User, SystemSettings } from './types';

export const INITIAL_OPDS: OPD[] = [
  { id: '1', name: 'Dinas Pendidikan, Pemuda dan Olahraga', paguMurni: 445394 },
  { id: '2', name: 'Cabang Dinas Pendidikan, Pemuda dan Olahraga Wilayah I', paguMurni: 894 },
  { id: '3', name: 'Cabang Dinas Pendidikan, Pemuda dan Olahraga Wilayah II', paguMurni: 1227 },
  { id: '4', name: 'Cabang Dinas Pendidikan, Pemuda dan Olahraga Wilayah III', paguMurni: 395 },
  { id: '5', name: 'Cabang Dinas Pendidikan, Pemuda dan Olahraga Wilayah IV', paguMurni: 599 },
  { id: '6', name: 'Cabang Dinas Pendidikan, Pemuda dan Olahraga Wilayah V', paguMurni: 451 },
  { id: '7', name: 'Cabang Dinas Pendidikan, Pemuda dan Olahraga Wilayah VI', paguMurni: 760 },
  { id: '8', name: 'Balai Teknologi Informasi dan Data Pendidikan', paguMurni: 489 },
  { id: '9', name: 'SMKN 3 Mataram', paguMurni: 89 },
  { id: '10', name: 'SMKN 5 Mataram', paguMurni: 926 },
  { id: '11', name: 'SMKN 1 Lingsar', paguMurni: 181 },
  { id: '12', name: 'SMKN 2 Kuripan', paguMurni: 12 },
  { id: '13', name: 'SMKN 1 Praya', paguMurni: 228 },
  { id: '14', name: 'SMKN 1 Selong', paguMurni: 154 },
  { id: '15', name: 'SMKN 1 Taliwang', paguMurni: 105 },
  { id: '16', name: 'SMKN 2 Sumbawa', paguMurni: 102 },
  { id: '17', name: 'SMKN 1 Dompu', paguMurni: 85 },
  { id: '18', name: 'SMKN 2 Kota Bima', paguMurni: 54 },
  { id: '19', name: 'SMKN 1 Donggo', paguMurni: 56 },
  { id: '20', name: 'Dinas Kesehatan', paguMurni: 100268 },
  { id: '21', name: 'Rumah Sakit Umum Daerah Provinsi NTB BLU', paguMurni: 721909 },
  { id: '22', name: 'Rumah Sakit Mutiara Sukma BLU', paguMurni: 37095 },
  { id: '23', name: 'Rumah Sakit H. L. Manambai Abdul Kadir BLU', paguMurni: 105767 },
  { id: '24', name: 'Rumah Sakit Mandalika BLU', paguMurni: 37092 },
  { id: '25', name: 'Rumah Sakit Mata BLU', paguMurni: 32880 },
  { id: '26', name: 'Balai Laboratorium Kesehatan, Pengujian dan Kalibrasi BLU', paguMurni: 5060 },
  { id: '27', name: 'Dinas Pekerjaan Umum, Penataan Ruang, Perumahan dan Kawasan Permukiman', paguMurni: 263786 },
  { id: '28', name: 'Balai Pemeliharaan Jalan Provinsi Pulau Lombok', paguMurni: 4525 },
  { id: '29', name: 'Balai Pemeliharaan Jalan Provinsi Pulau Sumbawa', paguMurni: 5719 },
  { id: '30', name: 'Balai Pengelolaan Sumber Daya Air Pulau Lombok', paguMurni: 8930 },
  { id: '31', name: 'Balai Pengelolaan Sumber Daya Air Pulau Sumbawa', paguMurni: 2513 },
  { id: '32', name: 'Balai Bina Jasa Konstruksi dan Pengujian Material', paguMurni: 601 },
  { id: '33', name: 'Satuan Polisi Pamong Praja', paguMurni: 6135 },
  { id: '34', name: 'Badan Penanggulangan Bencana Daerah', paguMurni: 4503 },
  { id: '35', name: 'Dinas Sosial, Pemberdayaan Perempuan dan Perlindungan Anak', paguMurni: 21790 },
  { id: '36', name: 'Pusat Pelayanan Sosial Bina Remaja Karya Wanita dan Penyandang Disabilitas Mirah Adi', paguMurni: 43 },
  { id: '37', name: 'Pusat Pelayanan Sosial Lanjut Usia Mandalika', paguMurni: 1364 },
  { id: '38', name: 'Perlindungan Perempuan dan Anak', paguMurni: 2221 },
  { id: '39', name: 'Pusat Pelayanan Sosial Bina Laras Muthmainnah', paguMurni: 1693 },
  { id: '40', name: 'Pusat Pelayanan Sosial Lanjut Usia Meci Angi', paguMurni: 800 },
  { id: '41', name: 'Dinas Tenaga Kerja dan Transmigrasi', paguMurni: 7268 },
  { id: '42', name: 'Balai Latihan Kerja (Skill Center)', paguMurni: 803 },
  { id: '43', name: 'Balai Pengawasan Ketenagakerjaan, Keselamatan, dan Kesehatan Kerja Pulau Lombok', paguMurni: 427 },
  { id: '44', name: 'Balai Pengawasan Ketenagakerjaan, Keselamatan, dan Kesehatan Kerja Pulau Sumbawa', paguMurni: 123 },
  { id: '45', name: 'Dinas Lingkungan Hidup dan Kehutanan', paguMurni: 30596 },
  { id: '46', name: 'Balai Laboratorium Lingkungan', paguMurni: 524 },
  { id: '47', name: 'Balai KPH Wilayah I', paguMurni: 483 },
  { id: '48', name: 'Balai KPH Wilayah II', paguMurni: 254 },
  { id: '49', name: 'Balai KPH Wilayah III', paguMurni: 214 },
  { id: '50', name: 'Balai KPH Wilayah IV', paguMurni: 251 },
  { id: '51', name: 'Balai KPH Wilayah V', paguMurni: 215 },
  { id: '52', name: 'Balai KPH Wilayah VI', paguMurni: 184 },
  { id: '53', name: 'Balai KPH Wilayah VII', paguMurni: 182 },
  { id: '54', name: 'Balai KPH Wilayah VIII', paguMurni: 149 },
  { id: '55', name: 'Tempat Pemrosesan Akhir (TPA) Sampah Regional Provinsi NTB', paguMurni: 6632 },
  { id: '56', name: 'Dinas Pemberdayaan Masyarakat, Pemerintahan Desa, Kependudukan dan Pencatatan Sipil', paguMurni: 10304 },
  { id: '57', name: 'Dinas Perhubungan', paguMurni: 5191 },
  { id: '58', name: 'Dinas Komunikasi, Informatika dan Statistik', paguMurni: 10771 },
  { id: '59', name: 'Dinas Koperasi Usaha Kecil dan Menengah', paguMurni: 5417 },
  { id: '60', name: 'Balai Pendidikan dan Pelatihan Koperasi Usaha Kecil dan Menengah', paguMurni: 1333 },
  { id: '61', name: 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu', paguMurni: 1834 },
  { id: '62', name: 'Dinas Kebudayaan', paguMurni: 1783 },
  { id: '63', name: 'Taman Budaya', paguMurni: 2304 },
  { id: '64', name: 'Museum Negeri', paguMurni: 1724 },
  { id: '65', name: 'Dinas Perpustakaan dan Kearsipan', paguMurni: 3108 },
  { id: '66', name: 'Dinas Kelautan dan Perikanan', paguMurni: 14882 },
  { id: '67', name: 'Balai Pengembangan Perikanan Budaya', paguMurni: 194 },
  { id: '68', name: 'Balai Laboratorium Pengujian dan Penerapan Mutu Hasil Perikanan dan Kelautan', paguMurni: 170 },
  { id: '69', name: 'Pelabuhan Perikanan Labuhan Lombok', paguMurni: 106 },
  { id: '70', name: 'Pelabuhan Perikanan Wilayah Pulau Sumbawa', paguMurni: 92 },
  { id: '71', name: 'Balai Pengelolaan Sumberdaya Kelautan dan Perikanan Wilayah Bima-Dompu', paguMurni: 326 },
  { id: '72', name: 'Balai Pengelolaan Sumberdaya Kelautan dan Perikanan Wilayah Sumbawa-Sumbawa Barat', paguMurni: 576 },
  { id: '73', name: 'Balai Pengelolaan Sumberdaya Kelautan dan Perikanan Wilayah Pulau Lombok', paguMurni: 346 },
  { id: '74', name: 'Pelabuhan Perikanan Tanjung Luar', paguMurni: 60 },
  { id: '75', name: 'Dinas Pariwisata dan Ekonomi Kreatif', paguMurni: 13030 },
  { id: '76', name: 'UPTD Destinasi Pariwisata Unggulan Gili Tramena', paguMurni: 863 },
  { id: '77', name: 'Dinas Peternakan dan Kesehatan Hewan', paguMurni: 18327 },
  { id: '78', name: 'Balai Pembibitan Ternak dan Hijauan Makanan Ternak Serading', paguMurni: 518 },
  { id: '79', name: 'Balai Inseminasi Buatan dan Pengembangan Pakan Ternak', paguMurni: 506 },
  { id: '80', name: 'Rumah Sakit Hewan dan Laboratorium Veteriner (BRSHLV)', paguMurni: 368 },
  { id: '81', name: 'Dinas Pertanian dan Ketahanan Pangan', paguMurni: 83511 },
  { id: '82', name: 'Balai Perlindungan Tanaman Pertanian (BPTP)', paguMurni: 509 },
  { id: '83', name: 'Balai Pengawasan dan Sertifikasi Benih Pertanian (BPSB-P)', paguMurni: 1119 },
  { id: '84', name: 'Balai Benih Induk Pertanian (BBI-P)', paguMurni: 1860 },
  { id: '85', name: 'Balai Pelatihan Pertanian', paguMurni: 995 },
  { id: '86', name: 'Sekolah Menengah Kejuruan Pembangunan Pertanian Negeri Mataram (SMKPPN Mataram)', paguMurni: 1956 },
  { id: '87', name: 'Sekolah Menengah Kejuruan Pembangunan Pertanian Negeri Bima (SMKPPN Bima)', paguMurni: 1184 },
  { id: '88', name: 'Balai Pengawasan Mutu dan Keamanan Pangan', paguMurni: 308 },
  { id: '89', name: 'Dinas Energi dan Sumber Daya Mineral', paguMurni: 4054 },
  { id: '90', name: 'Dinas Perindustrian dan Perdagangan', paguMurni: 11504 },
  { id: '91', name: 'Balai Kemasan, Promosi dan Pemasaran Produk Daerah', paguMurni: 1206 },
  { id: '92', name: 'Biro Umum dan Administrasi Pimpinan', paguMurni: 58056 },
  { id: '93', name: 'Biro Organisasi', paguMurni: 608 },
  { id: '94', name: 'Biro Hukum dan Hak Asasi Manusia', paguMurni: 9119 },
  { id: '95', name: 'Biro Pemerintahan dan Otonomi Daerah', paguMurni: 517 },
  { id: '96', name: 'Biro Kesejahteraan Rakyat', paguMurni: 44433 },
  { id: '97', name: 'Biro Perekonomian dan Administrasi Pembangunan', paguMurni: 4313 },
  { id: '98', name: 'Biro Pengadaan Barang dan Jasa', paguMurni: 1447 },
  { id: '99', name: 'Sekretariat Dewan Perwakilan Rakyat Daerah', paguMurni: 85486 },
  { id: '100', name: 'Badan Perencanaan Pembangunan Daerah', paguMurni: 14390 },
  { id: '101', name: 'Badan Keuangan dan Aset Daerah', paguMurni: 33814 },
  { id: '102', name: 'Badan Pendapatan Daerah', paguMurni: 11027 },
  { id: '103', name: 'Unit Pelayanan Pajak dan Retribusi Daerah Wilayah I BLU', paguMurni: 6784 },
  { id: '104', name: 'Unit Pelayanan Pajak dan Retribusi Daerah Wilayah II BLU', paguMurni: 2028 },
  { id: '105', name: 'Unit Pelayanan Pajak dan Retribusi Daerah Wilayah III BLU', paguMurni: 2049 },
  { id: '106', name: 'Unit Pelayanan Pajak dan Retribusi Daerah Wilayah IV BLU', paguMurni: 3237 },
  { id: '107', name: 'Unit Pelayanan Pajak dan Retribusi Daerah Wilayah V BLU', paguMurni: 4366 },
  { id: '108', name: 'Badan Kepegawaian Daerah', paguMurni: 2607 },
  { id: '109', name: 'Badan Pengembangan Sumber Daya Manusia Daerah', paguMurni: 13144 },
  { id: '110', name: 'Badan Riset dan Inovasi Daerah', paguMurni: 6343 },
  { id: '111', name: 'Badan Penghubung Daerah', paguMurni: 4726 },
  { id: '112', name: 'Inspektorat', paguMurni: 31221 },
  { id: '113', name: 'Badan Kesatuan Bangsa dan Politik Dalam Negeri', paguMurni: 34528 },
];

export const MOCK_USER: User = {
  id: 'user-1',
  name: 'Marga Sulkifli Rayes., S.IP',
  role: Role.ADMIN_PBJ,
};

export const DEFAULT_SETTINGS: SystemSettings = {
  pejabatNama: 'Marga Sulkifli Rayes., S.IP',
  pejabatNip: '19690922 200003 1 008',
  pejabatJabatan: 'Kepala Biro Pengadaan Barang dan Jasa',
  ta: '2026'
};

export const STATUS_COLORS = {
  critical: 'bg-[#FF0000] text-white', // 0-50%
  warning: 'bg-[#FFFF00] text-black', // 51-99%
  success: 'bg-[#00B050] text-white', // 100%
  over: 'bg-[#00B0F0] text-white',    // >100%
};
